name: Fly Volume Backup

on:
  schedule:
    - cron: "17 09 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  snapshot:
    name: Snapshot production data
    runs-on: ubuntu-latest
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl volumes snapshots create vol_458gx3x6w3ek27x4 --app runner-watch-ratimics
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
